# Generated by Django 3.2.3 on 2021-06-03 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=100)),
                ('etage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('ville', models.CharField(max_length=60)),
                ('poste', models.CharField(max_length=60)),
                ('salaire', models.FloatField()),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='api.department')),
            ],
        ),
    ]
